#!/usr/bin/env python3
"""Build/check dependency-free bundles, content-addressed PWA and deploy-only dist.

Runtime inputs, not a manually maintained version, determine the release.
No source file, test or private local artifact is copied into the Pages payload.
"""
from pathlib import Path
import argparse
import hashlib
import json
import re

ROOT = Path(__file__).resolve().parents[1]
OUTPUTS = {'styles': 'css/rhw-app.css', 'dashboard': 'js/rhw-dashboard.js', 'workspaces': 'js/rhw-workspaces.js'}
REVISION_MARKER = re.compile(r'^/\* GENERATED release revision: [^\n]+ \*/\n')
ASSET_QUERY = re.compile(r'((?:href|src)="\./(?:css/rhw-app|js/(?:build-info|00-bootstrap|rhw-dashboard))\.(?:css|js))(?:\?[^\"]*)?"')


def route_source(root):
    model = json.loads((root / 'scripts/app-routes.json').read_text())
    for workspace, nodes in model['routes'].items():
        if not nodes or len(set(nodes)) != len(nodes):
            raise ValueError(f'Invalid routes for {workspace}')
    routes = {f'{workspace}/{node}' for workspace, nodes in model['routes'].items() for node in nodes}
    if any(old in routes or new not in routes for old, new in model['legacyRedirects'].items()):
        raise ValueError('Legacy redirects must point to a current route')
    return ('/* GENERATED from scripts/app-routes.json. First node is the default. */\n'
            '(function () {\n  const model = ' + json.dumps(model, indent=2) + ';\n'
            '  Object.values(model.routes).forEach(Object.freeze);\n'
            '  Object.freeze(model.routes); Object.freeze(model.legacyRedirects);\n'
            '  globalThis.RHW_ROUTES = Object.freeze(model);\n})();\n')


def build(root=ROOT):
    assets = json.loads((root / 'scripts/runtime-assets.json').read_text())
    generated = {'js/core/routes.js': route_source(root)}
    metrics = {}
    for group, output in OUTPUTS.items():
        paths = [entry.removeprefix('./') for entry in assets[group]]
        if len(paths) != len(set(paths)):
            raise ValueError(f'Duplicate {group} entry')
        parts = ['/* GENERATED by scripts/build_app_assets.py. Edit the manifest sources. */\n']
        for entry in paths:
            path = (root / entry).resolve()
            if not path.is_relative_to(root) or (entry not in generated and not path.is_file()):
                raise ValueError(f'Invalid asset: {entry}')
            source = generated[entry] if entry in generated else path.read_text()
            parts.append(f'\n/* SOURCE: {entry} */\n{source}\n')
            if group != 'styles':
                parts.append(';\n')
        generated[output] = ''.join(parts)
        metrics[output] = {'sources': len(paths), 'bytes': len(generated[output].encode()),
                           'sha256': hashlib.sha256(generated[output].encode()).hexdigest()}
    shell = ['./', './index.html', './manifest.webmanifest', './js/build-info.js', './js/00-bootstrap.js',
             *['./' + p for p in OUTPUTS.values()], './assets/discovery-status.json',
             './assets/rhw-crest.png', './assets/rhw-forum-logo.png', './assets/favicon.png', './assets/apple-touch-icon.png',
             './assets/pwa-icon-192.png', './assets/pwa-icon-512.png', './assets/pwa-icon-maskable-512.png',
             *['./' + str(p.relative_to(root)) for p in sorted((root / 'assets/fonts').glob('*')) if p.suffix in {'.woff2', '.woff', '.ttf'}]]
    generated['js/app-shell.js'] = '/* GENERATED offline shell. */\nself.RHW_APP_SHELL = ' + json.dumps(shell, indent=2) + ';\n'
    generated['assets/build-assets.json'] = json.dumps(metrics, indent=2) + '\n'
    index = ASSET_QUERY.sub(r'\1"', (root / 'index.html').read_text())
    worker = REVISION_MARKER.sub('', (root / 'sw.js').read_text())
    inputs = {ref.removeprefix('./'): (root / ref).read_bytes()
              for ref in shell if ref not in {'./', './index.html', './js/build-info.js'} and ref.removeprefix('./') not in generated}
    inputs.update({path: text.encode() for path, text in generated.items()})
    inputs.update({'index.html': index.encode(), 'sw.js': worker.encode()})
    digest = hashlib.sha256()
    for path, data in sorted(inputs.items()):
        digest.update(path.encode() + b'\0' + str(len(data)).encode() + b'\0' + data)
    revision = 'sha256-' + digest.hexdigest()[:20]
    generated['js/build-info.js'] = ('/* GENERATED content revision; do not edit. */\n'
        'globalThis.RHW_BUILD = Object.freeze({\n'
        f"  revision: '{revision}',\n  repository: 'PhyteHQ/RHW',\n  branch: 'main'\n}});\n")
    generated['index.html'] = ASSET_QUERY.sub(lambda m: f'{m.group(1)}?v={revision}"', index)
    generated['sw.js'] = f'/* GENERATED release revision: {revision} */\n' + worker
    return generated, shell


def package_dist(generated, shell, root=ROOT):
    target = root / 'dist'
    files = {ref.removeprefix('./') for ref in shell if ref != './'}
    files.update({'sw.js', 'js/app-shell.js', 'assets/build-assets.json'})
    files.update(str(p.relative_to(root)) for p in (root / 'assets/fonts').glob('*-OFL.txt'))
    unexpected = {str(p.relative_to(target)) for p in target.rglob('*') if p.is_file()} - files - {'.nojekyll'}
    if unexpected:
        raise ValueError(f'dist contains unexpected files; use a fresh output directory: {sorted(unexpected)}')
    for name in sorted(files):
        path = target / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(generated[name].encode() if name in generated else (root / name).read_bytes())
    (target / '.nojekyll').write_text('')
    print(f'Packaged {len(files) + 1} runtime/license files in dist/.')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--dist', action='store_true', help='Package only deployed files in dist/')
    args = parser.parse_args()
    stale = []
    generated, shell = build()
    for name, text in generated.items():
        path = ROOT / name
        if args.check:
            if not path.exists() or path.read_text() != text:
                stale.append(name)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)
    if stale:
        raise SystemExit('Stale app assets; run python3 scripts/build_app_assets.py: ' + ', '.join(stale))
    if args.dist:
        package_dist(generated, shell)
    print('App assets verified.' if args.check else 'Built app bundles, routes and content-addressed offline shell.')


if __name__ == '__main__':
    main()
