#!/usr/bin/env python3
"""Build the static app from one ordered manifest, without build dependencies.

Classic script scope and CSS cascade order are preserved. Sources stay editable;
only three application bundles plus build metadata/bootstrap are requested.
Run --check in CI to reject stale generated files, including the offline shell.
"""
from pathlib import Path
import argparse
import hashlib
import json
import re

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / 'scripts/runtime-assets.json'
OUTPUTS = {'styles': 'css/rhw-app.css', 'dashboard': 'js/rhw-dashboard.js', 'workspaces': 'js/rhw-workspaces.js'}


def build():
    assets = json.loads(MANIFEST.read_text())
    generated = {}
    metrics = {}
    for group, output in OUTPUTS.items():
        paths = assets[group]
        if len(paths) != len(set(paths)):
            raise ValueError(f'Duplicate {group} entry')
        parts = ['/* GENERATED by scripts/build_app_assets.py. Edit the manifest sources. */\n']
        for entry in paths:
            path = (ROOT / entry).resolve()
            if not path.is_relative_to(ROOT) or not path.is_file():
                raise ValueError(f'Invalid asset: {entry}')
            source = path.read_text()
            parts.append(f'\n/* SOURCE: {entry} */\n{source}\n')
            if group != 'styles':
                parts.append(';\n')
        generated[output] = ''.join(parts)
        metrics[output] = {'sources': len(paths), 'bytes': len(generated[output].encode()),
                           'sha256': hashlib.sha256(generated[output].encode()).hexdigest()}
    shell = ['./', './index.html', './manifest.webmanifest', './js/build-info.js', './js/00-bootstrap.js',
             *['./' + p for p in OUTPUTS.values()], './assets/discovery-status.json',
             './assets/rhw-crest.png', './assets/favicon.png', './assets/apple-touch-icon.png',
             './assets/pwa-icon-192.png', './assets/pwa-icon-512.png', './assets/pwa-icon-maskable-512.png',
             *['./' + str(p.relative_to(ROOT)) for p in sorted((ROOT / 'assets/fonts').glob('*')) if p.suffix in {'.woff2', '.woff', '.ttf'}]]
    generated['js/app-shell.js'] = '/* GENERATED offline shell. */\nself.RHW_APP_SHELL = ' + json.dumps(shell, indent=2) + ';\n'
    generated['assets/build-assets.json'] = json.dumps(metrics, indent=2) + '\n'
    revision = re.search(r"revision:\s*'([^']+)'", (ROOT / 'js/build-info.js').read_text()).group(1)
    generated['index.html'] = re.sub(
        r'((?:href|src)="\./(?:css/rhw-app|js/(?:build-info|00-bootstrap|rhw-dashboard))\.(?:css|js))(?:\?[^\"]*)?"',
        lambda match: f'{match.group(1)}?v={revision}"', (ROOT / 'index.html').read_text())
    return generated


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    stale = []
    for name, text in build().items():
        path = ROOT / name
        if args.check:
            if not path.exists() or path.read_text() != text:
                stale.append(name)
        else:
            path.write_text(text)
    if stale:
        raise SystemExit('Stale app assets; run python3 scripts/build_app_assets.py: ' + ', '.join(stale))
    print('App assets verified.' if args.check else 'Built app styles, dashboard, workspaces and offline shell.')


if __name__ == '__main__':
    main()
